# Dependencies
# markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
url:              http://portlandcodeschool.github.io/frontend
baseurl:          /frontend

title:            'Front End Developer'
tagline:          'Portland Code School'
description:      'Front End Developer Class'
timezone:         GMT
sass: 
  sass_dir:         _sass
author1:
  name:           'Al Zimmerman'
  url:            'https://github.com/auraelius'


# Custom vars
version:          2.0.0